// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/netgui/v1/netgui.proto

// Контракт управления службой net-svc.
//
// Согласно ADR-004 это продукт первого класса, а не деталь реализации GUI:
// на нём говорят и net-cli, и net-gui, и будущий web UI для Linux server
// edition. Принцип P1 (headless-first) означает, что любое действие
// интерфейса выражается вызовом отсюда.
//
// Правило совместимости: изменения только аддитивные. Номера полей никогда
// не переиспользуются — удалённые помечаются reserved. GUI и служба
// обновляются независимо, и старый клиент не должен ломаться о новую службу.

package netguiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Тип транспорта наружу.
type Kind int32

const (
	Kind_KIND_UNSPECIFIED Kind = 0
	Kind_KIND_SOCKS5      Kind = 1
	Kind_KIND_HYSTERIA2   Kind = 2
	Kind_KIND_WIREGUARD   Kind = 3
	// AmneziaWG отличается от WireGuard только набором параметров обфускации,
	// но выделен отдельным значением намеренно: пользователю важно видеть в
	// списке, какой из двух профилей замаскирован, а какой нет.
	Kind_KIND_AMNEZIAWG Kind = 4
	Kind_KIND_VLESS     Kind = 5 // Дальше: KIND_TROJAN, KIND_SHADOWSOCKS, KIND_TUIC
)

// Enum value maps for Kind.
var (
	Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_SOCKS5",
		2: "KIND_HYSTERIA2",
		3: "KIND_WIREGUARD",
		4: "KIND_AMNEZIAWG",
		5: "KIND_VLESS",
	}
	Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"KIND_SOCKS5":      1,
		"KIND_HYSTERIA2":   2,
		"KIND_WIREGUARD":   3,
		"KIND_AMNEZIAWG":   4,
		"KIND_VLESS":       5,
	}
)

func (x Kind) Enum() *Kind {
	p := new(Kind)
	*p = x
	return p
}

func (x Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_netgui_v1_netgui_proto_enumTypes[0].Descriptor()
}

func (Kind) Type() protoreflect.EnumType {
	return &file_proto_netgui_v1_netgui_proto_enumTypes[0]
}

func (x Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Kind.Descriptor instead.
func (Kind) EnumDescriptor() ([]byte, []int) {
	return file_proto_netgui_v1_netgui_proto_rawDescGZIP(), []int{0}
}

// Что сделать с соединением.
type Action int32

const (
	Action_ACTION_UNSPECIFIED Action = 0
	Action_ACTION_PROXY       Action = 1
	Action_ACTION_DIRECT      Action = 2
	Action_ACTION_BLOCK       Action = 3
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_PROXY",
		2: "ACTION_DIRECT",
		3: "ACTION_BLOCK",
	}
	Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_PROXY":       1,
		"ACTION_DIRECT":      2,
		"ACTION_BLOCK":       3,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_netgui_v1_netgui_proto_enumTypes[1].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_proto_netgui_v1_netgui_proto_enumTypes[1]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_proto_netgui_v1_netgui_proto_rawDescGZIP(), []int{1}
}

// Фаза сессии. Соответствует конечному автомату из 03-architecture.md §6.2.
type SessionState int32

const (
	SessionState_SESSION_STATE_UNSPECIFIED SessionState = 0
	SessionState_SESSION_STATE_IDLE        SessionState = 1
	SessionState_SESSION_STATE_CONNECTING  SessionState = 2
	SessionState_SESSION_STATE_CONNECTED   SessionState = 3 // И-9/И-10: DEGRADED, FAILING, FAILED
)

// Enum value maps for SessionState.
var (
	SessionState_name = map[int32]string{
		0: "SESSION_STATE_UNSPECIFIED",
		1: "SESSION_STATE_IDLE",
		2: "SESSION_STATE_CONNECTING",
		3: "SESSION_STATE_CONNECTED",
	}
	SessionState_value = map[string]int32{
		"SESSION_STATE_UNSPECIFIED": 0,
		"SESSION_STATE_IDLE":        1,
		"SESSION_STATE_CONNECTING":  2,
		"SESSION_STATE_CONNECTED":   3,
	}
)

func (x SessionState) Enum() *SessionState {
	p := new(SessionState)
	*p = x
	return p
}

func (x SessionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_netgui_v1_netgui_proto_enumTypes[2].Descriptor()
}

func (SessionState) Type() protoreflect.EnumType {
	return &file_proto_netgui_v1_netgui_proto_enumTypes[2]
}

func (x SessionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionState.Descriptor instead.
func (SessionState) EnumDescriptor() ([]byte, []int) {
	return file_proto_netgui_v1_netgui_proto_rawDescGZIP(), []int{2}
}

// Режим работы соединения.
//
// Из трёх режимов задания здесь два. Системный прокси — не отдельный способ
// передачи трафика, а лишь настройка Windows поверх режима «прокси»;
// он появится в И-11 и получит своё значение.
type Mode int32

const (
	Mode_MODE_UNSPECIFIED Mode = 0
	// MODE_PROXY — локальный прокси. Приложения направляются на него вручную.
	// Умолчание: пустое значение означает именно его, поэтому старый клиент,
	// не знающий о режимах, продолжает работать как прежде.
	Mode_MODE_PROXY Mode = 1
	// MODE_TUNNEL — сетевой адаптер TUN: весь трафик системы идёт через
	// туннель без настройки отдельных приложений.
	//
	// ⚠️ Требует прав администратора у СЛУЖБЫ, а не у клиента.
	Mode_MODE_TUNNEL Mode = 2
)

// Enum value maps for Mode.
var (
	Mode_name = map[int32]string{
		0: "MODE_UNSPECIFIED",
		1: "MODE_PROXY",
		2: "MODE_TUNNEL",
	}
	Mode_value = map[string]int32{
		"MODE_UNSPECIFIED": 0,
		"MODE_PROXY":       1,
		"MODE_TUNNEL":      2,
	}
)

func (x Mode) Enum() *Mode {
	p := new(Mode)
	*p = x
	return p
}

func (x Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_netgui_v1_netgui_proto_enumTypes[3].Descriptor()
}

func (Mode) Type() protoreflect.EnumType {
	return &file_proto_netgui_v1_netgui_proto_enumTypes[3]
}

func (x Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mode.Descriptor instead.
func (Mode) EnumDescriptor() ([]byte, []int) {
	return file_proto_netgui_v1_netgui_proto_rawDescGZIP(), []int{3}
}

// Профиль подключения — декларативное описание пути наружу.
//
// ⚠️ Мера S3 (ADR-006): служба принимает ТОЛЬКО такое описание.
// Возможности передать сырой конфиг ядра не существует.
type Profile struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind     Kind                   `protobuf:"varint,3,opt,name=kind,proto3,enum=netgui.v1.Kind" json:"kind,omitempty"`
	Server   string                 `protobuf:"bytes,4,opt,name=server,proto3" json:"server,omitempty"`
	Port     uint32                 `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"` // проверяется на диапазон uint16 на стороне службы
	Username string                 `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	// password передаётся ТОЛЬКО в сторону службы.
	//
	// В ответах служба всегда возвращает пустую строку: секреты не покидают
	// её (мера S6). Интерфейсу пароль не нужен — ему нужно знать, задан ли он,
	// для чего есть has_secrets.
	//
	// При изменении существующего профиля пустое значение означает «оставить
	// прежний секрет». Иначе редактирование имени стирало бы пароль: клиент
	// не может прислать то, чего никогда не получал.
	Password string `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`
	// has_secrets сообщает, задан ли у профиля секрет.
	//
	// Заполняется службой в ответах. Позволяет показать «пароль задан»,
	// не передавая самого пароля.
	HasSecrets    bool `protobuf:"varint,8,opt,name=has_secrets,json=hasSecrets,proto3" json:"has_secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_proto_netgui_v1_netgui_proto_rawDescGZIP(), []int{0}
}

func (x *Profile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Profile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Profile) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_KIND_UNSPECIFIED
}

func (x *Profile) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *Profile) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Profile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Profile) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Profile) GetHasSecrets() bool {
	if x != nil {
		return x.HasSecrets
	}
	return false
}

// Предикат соединения. Пустой матчер недопустим.
type Matcher struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        []string               `protobuf:"bytes,1,rep,name=domain,proto3" json:"domain,omitempty"`
	DomainSuffix  []string               `protobuf:"bytes,2,rep,name=domain_suffix,json=domainSuffix,proto3" json:"domain_suffix,omitempty"`
	IpCidr        []string               `protobuf:"bytes,3,rep,name=ip_cidr,json=ipCidr,proto3" json:"ip_cidr,omitempty"` // И-7: process_path, domain_regex, geoip, port, l4_protocol
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Matcher) Reset() {
	*x = Matcher{}
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Matcher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Matcher) ProtoMessage() {}

func (x *Matcher) ProtoReflect() protoreflect.Message {
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Matcher.ProtoReflect.Descriptor instead.
func (*Matcher) Descriptor() ([]byte, []int) {
	return file_proto_netgui_v1_netgui_proto_rawDescGZIP(), []int{1}
}

func (x *Matcher) GetDomain() []string {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *Matcher) GetDomainSuffix() []string {
	if x != nil {
		return x.DomainSuffix
	}
	return nil
}

func (x *Matcher) GetIpCidr() []string {
	if x != nil {
		return x.IpCidr
	}
	return nil
}

type Rule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matcher       *Matcher               `protobuf:"bytes,1,opt,name=matcher,proto3" json:"matcher,omitempty"`
	Action        Action                 `protobuf:"varint,2,opt,name=action,proto3,enum=netgui.v1.Action" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_proto_netgui_v1_netgui_proto_rawDescGZIP(), []int{2}
}

func (x *Rule) GetMatcher() *Matcher {
	if x != nil {
		return x.Matcher
	}
	return nil
}

func (x *Rule) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ACTION_UNSPECIFIED
}

// Политика маршрутизации.
//
// Порядок правил значим: выигрывает первое совпадение.
// default_action = ACTION_DIRECT → «только выбранное через туннель»
// default_action = ACTION_PROXY  → «всё через туннель, кроме выбранного»
type Policy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DefaultAction Action                 `protobuf:"varint,1,opt,name=default_action,json=defaultAction,proto3,enum=netgui.v1.Action" json:"default_action,omitempty"`
	Rules         []*Rule                `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_proto_netgui_v1_netgui_proto_rawDescGZIP(), []int{3}
}

func (x *Policy) GetDefaultAction() Action {
	if x != nil {
		return x.DefaultAction
	}
	return Action_ACTION_UNSPECIFIED
}

func (x *Policy) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         SessionState           `protobuf:"varint,1,opt,name=state,proto3,enum=netgui.v1.SessionState" json:"state,omitempty"`
	ProfileId     string                 `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	ListenAddress string                 `protobuf:"bytes,3,opt,name=listen_address,json=listenAddress,proto3" json:"listen_address,omitempty"` // "127.0.0.1:1080"
	Policy        *Policy                `protobuf:"bytes,4,opt,name=policy,proto3" json:"policy,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"` // непустое, если последняя попытка не удалась
	// Режим текущего соединения. Интерфейс обязан показывать его: «подключено»
	// означает разное в режиме прокси и в режиме туннеля, и путать их — значит
	// вводить пользователя в заблуждение относительно того, куда идёт трафик.
	Mode          Mode `protobuf:"varint,6,opt,name=mode,proto3,enum=netgui.v1.Mode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_proto_netgui_v1_netgui_proto_rawDescGZIP(), []int{4}
}

func (x *Status) GetState() SessionState {
	if x != nil {
		return x.State
	}
	return SessionState_SESSION_STATE_UNSPECIFIED
}

func (x *Status) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *Status) GetListenAddress() string {
	if x != nil {
		return x.ListenAddress
	}
	return ""
}

func (x *Status) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *Status) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Status) GetMode() Mode {
	if x != nil {
		return x.Mode
	}
	return Mode_MODE_UNSPECIFIED
}

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientName    string                 `protobuf:"bytes,1,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	ClientVersion string                 `protobuf:"bytes,2,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_proto_netgui_v1_netgui_proto_rawDescGZIP(), []int{5}
}

func (x *HelloRequest) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *HelloRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

type HelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerVersion string                 `protobuf:"bytes,1,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	// Версия контракта. Клиент с большим значением, чем у службы, обязан
	// сообщить пользователю «обновите службу», а не падать по таймауту.
	ApiVersion    uint32 `protobuf:"varint,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_proto_netgui_v1_netgui_proto_rawDescGZIP(), []int{6}
}

func (x *HelloResponse) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *HelloResponse) GetApiVersion() uint32 {
	if x != nil {
		return x.ApiVersion
	}
	return 0
}

type ImportProfileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id пустой означает «выдать самостоятельно»: только служба знает, какие
	// идентификаторы уже заняты. Графический интерфейс так и делает; net-cli
	// задаёт идентификатор явно, потому что им же потом и пользуются в командах.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// name пустое означает «взять из содержимого»: в ссылках имя лежит во
	// фрагменте после решётки.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// content — ссылка (vless://, hysteria2://, socks5://) либо текст файла
	// конфигурации wg-quick. Тип определяется по содержимому, а не по имени
	// файла: имя пользователь волен изменить, содержимое — нет.
	Content       string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportProfileRequest) Reset() {
	*x = ImportProfileRequest{}
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportProfileRequest) ProtoMessage() {}

func (x *ImportProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportProfileRequest.ProtoReflect.Descriptor instead.
func (*ImportProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_netgui_v1_netgui_proto_rawDescGZIP(), []int{7}
}

func (x *ImportProfileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImportProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImportProfileRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ImportProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportProfileResponse) Reset() {
	*x = ImportProfileResponse{}
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportProfileResponse) ProtoMessage() {}

func (x *ImportProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportProfileResponse.ProtoReflect.Descriptor instead.
func (*ImportProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_netgui_v1_netgui_proto_rawDescGZIP(), []int{8}
}

func (x *ImportProfileResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type ListProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesRequest) Reset() {
	*x = ListProfilesRequest{}
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesRequest) ProtoMessage() {}

func (x *ListProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesRequest.ProtoReflect.Descriptor instead.
func (*ListProfilesRequest) Descriptor() ([]byte, []int) {
	return file_proto_netgui_v1_netgui_proto_rawDescGZIP(), []int{9}
}

type ListProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*Profile             `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesResponse) Reset() {
	*x = ListProfilesResponse{}
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesResponse) ProtoMessage() {}

func (x *ListProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesResponse.ProtoReflect.Descriptor instead.
func (*ListProfilesResponse) Descriptor() ([]byte, []int) {
	return file_proto_netgui_v1_netgui_proto_rawDescGZIP(), []int{10}
}

func (x *ListProfilesResponse) GetProfiles() []*Profile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

// Put создаёт профиль или заменяет существующий с тем же id.
type PutProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutProfileRequest) Reset() {
	*x = PutProfileRequest{}
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutProfileRequest) ProtoMessage() {}

func (x *PutProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutProfileRequest.ProtoReflect.Descriptor instead.
func (*PutProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_netgui_v1_netgui_proto_rawDescGZIP(), []int{11}
}

func (x *PutProfileRequest) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type PutProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutProfileResponse) Reset() {
	*x = PutProfileResponse{}
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutProfileResponse) ProtoMessage() {}

func (x *PutProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutProfileResponse.ProtoReflect.Descriptor instead.
func (*PutProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_netgui_v1_netgui_proto_rawDescGZIP(), []int{12}
}

func (x *PutProfileResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type RemoveProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveProfileRequest) Reset() {
	*x = RemoveProfileRequest{}
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveProfileRequest) ProtoMessage() {}

func (x *RemoveProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveProfileRequest.ProtoReflect.Descriptor instead.
func (*RemoveProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_netgui_v1_netgui_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveProfileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemoveProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveProfileResponse) Reset() {
	*x = RemoveProfileResponse{}
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveProfileResponse) ProtoMessage() {}

func (x *RemoveProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveProfileResponse.ProtoReflect.Descriptor instead.
func (*RemoveProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_netgui_v1_netgui_proto_rawDescGZIP(), []int{14}
}

type ConnectRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ProfileId string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Policy    *Policy                `protobuf:"bytes,2,opt,name=policy,proto3" json:"policy,omitempty"`
	// Порт локального inbound. 0 — выбрать свободный автоматически.
	ListenPort uint32 `protobuf:"varint,3,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	// Режим. MODE_UNSPECIFIED означает MODE_PROXY: клиент, собранный до
	// появления режимов, продолжает работать без изменений.
	Mode          Mode `protobuf:"varint,4,opt,name=mode,proto3,enum=netgui.v1.Mode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_proto_netgui_v1_netgui_proto_rawDescGZIP(), []int{15}
}

func (x *ConnectRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *ConnectRequest) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *ConnectRequest) GetListenPort() uint32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *ConnectRequest) GetMode() Mode {
	if x != nil {
		return x.Mode
	}
	return Mode_MODE_UNSPECIFIED
}

type DisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectRequest) Reset() {
	*x = DisconnectRequest{}
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectRequest) ProtoMessage() {}

func (x *DisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectRequest.ProtoReflect.Descriptor instead.
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return file_proto_netgui_v1_netgui_proto_rawDescGZIP(), []int{16}
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_netgui_v1_netgui_proto_rawDescGZIP(), []int{17}
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_netgui_v1_netgui_proto_rawDescGZIP(), []int{18}
}

type Event struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	UnixNano int64                  `protobuf:"varint,1,opt,name=unix_nano,json=unixNano,proto3" json:"unix_nano,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Event_StatusChanged
	Payload       isEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_netgui_v1_netgui_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_netgui_v1_netgui_proto_rawDescGZIP(), []int{19}
}

func (x *Event) GetUnixNano() int64 {
	if x != nil {
		return x.UnixNano
	}
	return 0
}

func (x *Event) GetPayload() isEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetStatusChanged() *Status {
	if x != nil {
		if x, ok := x.Payload.(*Event_StatusChanged); ok {
			return x.StatusChanged
		}
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_StatusChanged struct {
	StatusChanged *Status `protobuf:"bytes,2,opt,name=status_changed,json=statusChanged,proto3,oneof"` // И-9: metrics, log_line, failover_switched, all_nodes_down
}

func (*Event_StatusChanged) isEvent_Payload() {}

var File_proto_netgui_v1_netgui_proto protoreflect.FileDescriptor

const file_proto_netgui_v1_netgui_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/netgui/v1/netgui.proto\x12\tnetgui.v1\"\xd7\x01\n" +
	"\aProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x0f.netgui.v1.KindR\x04kind\x12\x16\n" +
	"\x06server\x18\x04 \x01(\tR\x06server\x12\x12\n" +
	"\x04port\x18\x05 \x01(\rR\x04port\x12\x1a\n" +
	"\busername\x18\x06 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\a \x01(\tR\bpassword\x12\x1f\n" +
	"\vhas_secrets\x18\b \x01(\bR\n" +
	"hasSecrets\"_\n" +
	"\aMatcher\x12\x16\n" +
	"\x06domain\x18\x01 \x03(\tR\x06domain\x12#\n" +
	"\rdomain_suffix\x18\x02 \x03(\tR\fdomainSuffix\x12\x17\n" +
	"\aip_cidr\x18\x03 \x03(\tR\x06ipCidr\"_\n" +
	"\x04Rule\x12,\n" +
	"\amatcher\x18\x01 \x01(\v2\x12.netgui.v1.MatcherR\amatcher\x12)\n" +
	"\x06action\x18\x02 \x01(\x0e2\x11.netgui.v1.ActionR\x06action\"i\n" +
	"\x06Policy\x128\n" +
	"\x0edefault_action\x18\x01 \x01(\x0e2\x11.netgui.v1.ActionR\rdefaultAction\x12%\n" +
	"\x05rules\x18\x02 \x03(\v2\x0f.netgui.v1.RuleR\x05rules\"\xe3\x01\n" +
	"\x06Status\x12-\n" +
	"\x05state\x18\x01 \x01(\x0e2\x17.netgui.v1.SessionStateR\x05state\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tR\tprofileId\x12%\n" +
	"\x0elisten_address\x18\x03 \x01(\tR\rlistenAddress\x12)\n" +
	"\x06policy\x18\x04 \x01(\v2\x11.netgui.v1.PolicyR\x06policy\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12#\n" +
	"\x04mode\x18\x06 \x01(\x0e2\x0f.netgui.v1.ModeR\x04mode\"V\n" +
	"\fHelloRequest\x12\x1f\n" +
	"\vclient_name\x18\x01 \x01(\tR\n" +
	"clientName\x12%\n" +
	"\x0eclient_version\x18\x02 \x01(\tR\rclientVersion\"W\n" +
	"\rHelloResponse\x12%\n" +
	"\x0eserver_version\x18\x01 \x01(\tR\rserverVersion\x12\x1f\n" +
	"\vapi_version\x18\x02 \x01(\rR\n" +
	"apiVersion\"T\n" +
	"\x14ImportProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"E\n" +
	"\x15ImportProfileResponse\x12,\n" +
	"\aprofile\x18\x01 \x01(\v2\x12.netgui.v1.ProfileR\aprofile\"\x15\n" +
	"\x13ListProfilesRequest\"F\n" +
	"\x14ListProfilesResponse\x12.\n" +
	"\bprofiles\x18\x01 \x03(\v2\x12.netgui.v1.ProfileR\bprofiles\"A\n" +
	"\x11PutProfileRequest\x12,\n" +
	"\aprofile\x18\x01 \x01(\v2\x12.netgui.v1.ProfileR\aprofile\"B\n" +
	"\x12PutProfileResponse\x12,\n" +
	"\aprofile\x18\x01 \x01(\v2\x12.netgui.v1.ProfileR\aprofile\"&\n" +
	"\x14RemoveProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x17\n" +
	"\x15RemoveProfileResponse\"\xa0\x01\n" +
	"\x0eConnectRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\x12)\n" +
	"\x06policy\x18\x02 \x01(\v2\x11.netgui.v1.PolicyR\x06policy\x12\x1f\n" +
	"\vlisten_port\x18\x03 \x01(\rR\n" +
	"listenPort\x12#\n" +
	"\x04mode\x18\x04 \x01(\x0e2\x0f.netgui.v1.ModeR\x04mode\"\x13\n" +
	"\x11DisconnectRequest\"\x12\n" +
	"\x10GetStatusRequest\"\x12\n" +
	"\x10SubscribeRequest\"k\n" +
	"\x05Event\x12\x1b\n" +
	"\tunix_nano\x18\x01 \x01(\x03R\bunixNano\x12:\n" +
	"\x0estatus_changed\x18\x02 \x01(\v2\x11.netgui.v1.StatusH\x00R\rstatusChangedB\t\n" +
	"\apayload*y\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vKIND_SOCKS5\x10\x01\x12\x12\n" +
	"\x0eKIND_HYSTERIA2\x10\x02\x12\x12\n" +
	"\x0eKIND_WIREGUARD\x10\x03\x12\x12\n" +
	"\x0eKIND_AMNEZIAWG\x10\x04\x12\x0e\n" +
	"\n" +
	"KIND_VLESS\x10\x05*W\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fACTION_PROXY\x10\x01\x12\x11\n" +
	"\rACTION_DIRECT\x10\x02\x12\x10\n" +
	"\fACTION_BLOCK\x10\x03*\x80\x01\n" +
	"\fSessionState\x12\x1d\n" +
	"\x19SESSION_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SESSION_STATE_IDLE\x10\x01\x12\x1c\n" +
	"\x18SESSION_STATE_CONNECTING\x10\x02\x12\x1b\n" +
	"\x17SESSION_STATE_CONNECTED\x10\x03*=\n" +
	"\x04Mode\x12\x14\n" +
	"\x10MODE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"MODE_PROXY\x10\x01\x12\x0f\n" +
	"\vMODE_TUNNEL\x10\x022L\n" +
	"\x0eControlService\x12:\n" +
	"\x05Hello\x12\x17.netgui.v1.HelloRequest\x1a\x18.netgui.v1.HelloResponse2\xb7\x02\n" +
	"\x0eProfileService\x12G\n" +
	"\x04List\x12\x1e.netgui.v1.ListProfilesRequest\x1a\x1f.netgui.v1.ListProfilesResponse\x12B\n" +
	"\x03Put\x12\x1c.netgui.v1.PutProfileRequest\x1a\x1d.netgui.v1.PutProfileResponse\x12K\n" +
	"\x06Remove\x12\x1f.netgui.v1.RemoveProfileRequest\x1a .netgui.v1.RemoveProfileResponse\x12K\n" +
	"\x06Import\x12\x1f.netgui.v1.ImportProfileRequest\x1a .netgui.v1.ImportProfileResponse2\xc5\x01\n" +
	"\x0eSessionService\x127\n" +
	"\aConnect\x12\x19.netgui.v1.ConnectRequest\x1a\x11.netgui.v1.Status\x12=\n" +
	"\n" +
	"Disconnect\x12\x1c.netgui.v1.DisconnectRequest\x1a\x11.netgui.v1.Status\x12;\n" +
	"\tGetStatus\x12\x1b.netgui.v1.GetStatusRequest\x1a\x11.netgui.v1.Status2L\n" +
	"\fEventService\x12<\n" +
	"\tSubscribe\x12\x1b.netgui.v1.SubscribeRequest\x1a\x10.netgui.v1.Event0\x01B=Z;github.com/bbesport/net-gui-client/proto/netgui/v1;netguiv1b\x06proto3"

var (
	file_proto_netgui_v1_netgui_proto_rawDescOnce sync.Once
	file_proto_netgui_v1_netgui_proto_rawDescData []byte
)

func file_proto_netgui_v1_netgui_proto_rawDescGZIP() []byte {
	file_proto_netgui_v1_netgui_proto_rawDescOnce.Do(func() {
		file_proto_netgui_v1_netgui_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_netgui_v1_netgui_proto_rawDesc), len(file_proto_netgui_v1_netgui_proto_rawDesc)))
	})
	return file_proto_netgui_v1_netgui_proto_rawDescData
}

var file_proto_netgui_v1_netgui_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_netgui_v1_netgui_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_netgui_v1_netgui_proto_goTypes = []any{
	(Kind)(0),                     // 0: netgui.v1.Kind
	(Action)(0),                   // 1: netgui.v1.Action
	(SessionState)(0),             // 2: netgui.v1.SessionState
	(Mode)(0),                     // 3: netgui.v1.Mode
	(*Profile)(nil),               // 4: netgui.v1.Profile
	(*Matcher)(nil),               // 5: netgui.v1.Matcher
	(*Rule)(nil),                  // 6: netgui.v1.Rule
	(*Policy)(nil),                // 7: netgui.v1.Policy
	(*Status)(nil),                // 8: netgui.v1.Status
	(*HelloRequest)(nil),          // 9: netgui.v1.HelloRequest
	(*HelloResponse)(nil),         // 10: netgui.v1.HelloResponse
	(*ImportProfileRequest)(nil),  // 11: netgui.v1.ImportProfileRequest
	(*ImportProfileResponse)(nil), // 12: netgui.v1.ImportProfileResponse
	(*ListProfilesRequest)(nil),   // 13: netgui.v1.ListProfilesRequest
	(*ListProfilesResponse)(nil),  // 14: netgui.v1.ListProfilesResponse
	(*PutProfileRequest)(nil),     // 15: netgui.v1.PutProfileRequest
	(*PutProfileResponse)(nil),    // 16: netgui.v1.PutProfileResponse
	(*RemoveProfileRequest)(nil),  // 17: netgui.v1.RemoveProfileRequest
	(*RemoveProfileResponse)(nil), // 18: netgui.v1.RemoveProfileResponse
	(*ConnectRequest)(nil),        // 19: netgui.v1.ConnectRequest
	(*DisconnectRequest)(nil),     // 20: netgui.v1.DisconnectRequest
	(*GetStatusRequest)(nil),      // 21: netgui.v1.GetStatusRequest
	(*SubscribeRequest)(nil),      // 22: netgui.v1.SubscribeRequest
	(*Event)(nil),                 // 23: netgui.v1.Event
}
var file_proto_netgui_v1_netgui_proto_depIdxs = []int32{
	0,  // 0: netgui.v1.Profile.kind:type_name -> netgui.v1.Kind
	5,  // 1: netgui.v1.Rule.matcher:type_name -> netgui.v1.Matcher
	1,  // 2: netgui.v1.Rule.action:type_name -> netgui.v1.Action
	1,  // 3: netgui.v1.Policy.default_action:type_name -> netgui.v1.Action
	6,  // 4: netgui.v1.Policy.rules:type_name -> netgui.v1.Rule
	2,  // 5: netgui.v1.Status.state:type_name -> netgui.v1.SessionState
	7,  // 6: netgui.v1.Status.policy:type_name -> netgui.v1.Policy
	3,  // 7: netgui.v1.Status.mode:type_name -> netgui.v1.Mode
	4,  // 8: netgui.v1.ImportProfileResponse.profile:type_name -> netgui.v1.Profile
	4,  // 9: netgui.v1.ListProfilesResponse.profiles:type_name -> netgui.v1.Profile
	4,  // 10: netgui.v1.PutProfileRequest.profile:type_name -> netgui.v1.Profile
	4,  // 11: netgui.v1.PutProfileResponse.profile:type_name -> netgui.v1.Profile
	7,  // 12: netgui.v1.ConnectRequest.policy:type_name -> netgui.v1.Policy
	3,  // 13: netgui.v1.ConnectRequest.mode:type_name -> netgui.v1.Mode
	8,  // 14: netgui.v1.Event.status_changed:type_name -> netgui.v1.Status
	9,  // 15: netgui.v1.ControlService.Hello:input_type -> netgui.v1.HelloRequest
	13, // 16: netgui.v1.ProfileService.List:input_type -> netgui.v1.ListProfilesRequest
	15, // 17: netgui.v1.ProfileService.Put:input_type -> netgui.v1.PutProfileRequest
	17, // 18: netgui.v1.ProfileService.Remove:input_type -> netgui.v1.RemoveProfileRequest
	11, // 19: netgui.v1.ProfileService.Import:input_type -> netgui.v1.ImportProfileRequest
	19, // 20: netgui.v1.SessionService.Connect:input_type -> netgui.v1.ConnectRequest
	20, // 21: netgui.v1.SessionService.Disconnect:input_type -> netgui.v1.DisconnectRequest
	21, // 22: netgui.v1.SessionService.GetStatus:input_type -> netgui.v1.GetStatusRequest
	22, // 23: netgui.v1.EventService.Subscribe:input_type -> netgui.v1.SubscribeRequest
	10, // 24: netgui.v1.ControlService.Hello:output_type -> netgui.v1.HelloResponse
	14, // 25: netgui.v1.ProfileService.List:output_type -> netgui.v1.ListProfilesResponse
	16, // 26: netgui.v1.ProfileService.Put:output_type -> netgui.v1.PutProfileResponse
	18, // 27: netgui.v1.ProfileService.Remove:output_type -> netgui.v1.RemoveProfileResponse
	12, // 28: netgui.v1.ProfileService.Import:output_type -> netgui.v1.ImportProfileResponse
	8,  // 29: netgui.v1.SessionService.Connect:output_type -> netgui.v1.Status
	8,  // 30: netgui.v1.SessionService.Disconnect:output_type -> netgui.v1.Status
	8,  // 31: netgui.v1.SessionService.GetStatus:output_type -> netgui.v1.Status
	23, // 32: netgui.v1.EventService.Subscribe:output_type -> netgui.v1.Event
	24, // [24:33] is the sub-list for method output_type
	15, // [15:24] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_netgui_v1_netgui_proto_init() }
func file_proto_netgui_v1_netgui_proto_init() {
	if File_proto_netgui_v1_netgui_proto != nil {
		return
	}
	file_proto_netgui_v1_netgui_proto_msgTypes[19].OneofWrappers = []any{
		(*Event_StatusChanged)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_netgui_v1_netgui_proto_rawDesc), len(file_proto_netgui_v1_netgui_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_proto_netgui_v1_netgui_proto_goTypes,
		DependencyIndexes: file_proto_netgui_v1_netgui_proto_depIdxs,
		EnumInfos:         file_proto_netgui_v1_netgui_proto_enumTypes,
		MessageInfos:      file_proto_netgui_v1_netgui_proto_msgTypes,
	}.Build()
	File_proto_netgui_v1_netgui_proto = out.File
	file_proto_netgui_v1_netgui_proto_goTypes = nil
	file_proto_netgui_v1_netgui_proto_depIdxs = nil
}
