// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect(arg1:string,arg2:string):Promise<main.StatusView>;

export function Disconnect():Promise<main.StatusView>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetStatus():Promise<main.StatusView>;

export function ListProfiles():Promise<Array<main.ProfileView>>;

export function ShowWindow():Promise<void>;
