// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChooseProfileFile():Promise<string>;

export function Connect(arg1:string,arg2:string,arg3:string):Promise<main.StatusView>;

export function Disconnect():Promise<main.StatusView>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetStatus():Promise<main.StatusView>;

export function ImportProfileFromFile(arg1:string,arg2:string,arg3:string):Promise<main.ProfileResult>;

export function ImportProfileFromLink(arg1:string,arg2:string,arg3:string):Promise<main.ProfileResult>;

export function ListProfiles():Promise<Array<main.ProfileView>>;

export function RemoveProfile(arg1:string):Promise<main.ProfileResult>;

export function RenameProfile(arg1:string,arg2:string):Promise<main.ProfileResult>;

export function ShowWindow():Promise<void>;
