// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseProfileFile() {
  return window['go']['main']['app']['ChooseProfileFile']();
}

export function Connect(arg1, arg2, arg3) {
  return window['go']['main']['app']['Connect'](arg1, arg2, arg3);
}

export function Disconnect() {
  return window['go']['main']['app']['Disconnect']();
}

export function GetAppInfo() {
  return window['go']['main']['app']['GetAppInfo']();
}

export function GetStatus() {
  return window['go']['main']['app']['GetStatus']();
}

export function ImportProfileFromFile(arg1, arg2, arg3) {
  return window['go']['main']['app']['ImportProfileFromFile'](arg1, arg2, arg3);
}

export function ImportProfileFromLink(arg1, arg2, arg3) {
  return window['go']['main']['app']['ImportProfileFromLink'](arg1, arg2, arg3);
}

export function ListProfiles() {
  return window['go']['main']['app']['ListProfiles']();
}

export function RemoveProfile(arg1) {
  return window['go']['main']['app']['RemoveProfile'](arg1);
}

export function RenameProfile(arg1, arg2) {
  return window['go']['main']['app']['RenameProfile'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['app']['ShowWindow']();
}
