// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2) {
  return window['go']['main']['app']['Connect'](arg1, arg2);
}

export function Disconnect() {
  return window['go']['main']['app']['Disconnect']();
}

export function GetAppInfo() {
  return window['go']['main']['app']['GetAppInfo']();
}

export function GetStatus() {
  return window['go']['main']['app']['GetStatus']();
}

export function ListProfiles() {
  return window['go']['main']['app']['ListProfiles']();
}

export function ShowWindow() {
  return window['go']['main']['app']['ShowWindow']();
}
